<script setup lang="ts">
import{computed,ref}from'vue'
import{BookOpen,CheckCircle2,ChevronRight,Languages,MessageSquare,XCircle}from'lucide-vue-next'
import LessonAudioPlayer from'@/components/lesson/LessonAudioPlayer.vue'
import type{Lesson}from'@/types/course'
const props=defineProps<{lesson:Lesson}>();const answers=ref<Record<string,number>>({});const listened=ref<string[]>([])
const questions=computed(()=>props.lesson.blocks.filter(block=>block.type==='single_choice'))
const audioBlocks=computed(()=>props.lesson.blocks.filter(block=>block.type==='audio'&&block.required))
const answered=computed(()=>questions.value.filter(block=>answers.value[block.id]!==undefined).length)
const correct=computed(()=>questions.value.filter(block=>answers.value[block.id]===block.correctOption).length)
const canFinish=computed(()=>answered.value===questions.value.length&&audioBlocks.value.every(block=>listened.value.includes(block.id)))
function answer(id:string,index:number){answers.value[id]=index}
function markListened(id:string){if(!listened.value.includes(id))listened.value.push(id)}
</script>
<template><div class="player learning-player"><p class="eyebrow">Урок · {{lesson.duration}} минут · {{questions.length}} вопросов</p><h1>{{lesson.title}}</h1><article v-for="block in lesson.blocks" :key="block.id" :class="['player-block',block.type]"><h2 v-if="block.type==='heading'">{{block.content}}</h2><p v-else-if="block.type==='text'">{{block.content}}</p><aside v-else-if="block.type==='callout'"><MessageSquare/><div><b>{{block.title}}</b><p>{{block.content}}</p></div></aside><section v-else-if="block.type==='grammar'||block.type==='vocabulary'" class="player-theory"><component :is="block.type==='grammar'?BookOpen:Languages"/><div><small>{{block.type==='grammar'?'Теория':'Словарь'}}</small><h3>{{block.title}}</h3><p>{{block.content}}</p></div></section><LessonAudioPlayer v-else-if="block.type==='audio'" :src="block.audioUrl" :title="block.title" :transcript="block.transcript" @completed="markListened(block.id)"/><section v-else-if="block.type==='single_choice'" class="player-question"><small>{{block.title}}</small><h3>{{block.content}}</h3><button v-for="(option,index) in block.options" :key="option" :class="['answer',answers[block.id]===index&&'chosen',answers[block.id]!==undefined&&index===block.correctOption&&'correct',answers[block.id]===index&&index!==block.correctOption&&'wrong']" @click="answer(block.id,index)">{{option}}<CheckCircle2 v-if="answers[block.id]!==undefined&&index===block.correctOption"/><XCircle v-else-if="answers[block.id]===index&&index!==block.correctOption"/></button><div v-if="answers[block.id]!==undefined" :class="['answer-explanation',answers[block.id]===block.correctOption?'is-correct':'is-wrong']"><strong>{{answers[block.id]===block.correctOption?'Верно':'Нужно повторить правило'}}</strong><p>{{block.explanation}}</p></div></section></article><div class="lesson-result" v-if="answered"><span>Результат проверки</span><strong>{{correct}} из {{questions.length}}</strong><small v-if="answered<questions.length">Ответьте ещё на {{questions.length-answered}} вопрос(а)</small><small v-else-if="correct<questions.length">Разберите ошибки и попробуйте исправить ответы</small><small v-else>Все ответы верны — отличная работа</small></div><div class="player-footer"><span>{{answered}} из {{questions.length}} вопросов · {{listened.length}} из {{audioBlocks.length}} аудирований</span><button class="primary" :disabled="!canFinish">Завершить урок <ChevronRight/></button></div></div></template>