<script setup lang="ts">
import{computed,ref}from'vue'
import{useRoute}from'vue-router'
import{VueDraggable}from'vue-draggable-plus'
import{ArrowLeft,BookOpen,Brain,Check,ChevronRight,Dumbbell,Eye,GripVertical,Heading,Languages,LayoutTemplate,Link,ListChecks,MessageCircle,MessageSquare,Music2,Plus,Save,Settings2,ShieldAlert,Text,Trash2,Upload}from'lucide-vue-next'
import UiButton from'@/components/ui/button/UiButton.vue'
import UiSwitch from'@/components/ui/switch/UiSwitch.vue'
import LessonAudioPlayer from'@/components/lesson/LessonAudioPlayer.vue'
import{useCourseStore}from'@/stores/courses'
import type{BlockType,LessonBlock}from'@/types/course'
const route=useRoute(),store=useCourseStore();const found=computed(()=>store.findLesson(String(route.params.lessonId)))
const blocks=computed<LessonBlock[]>({get:()=>found.value?.lesson.blocks??[],set:value=>{if(found.value)found.value.lesson.blocks=value}})
const selectedId=ref('');const selected=computed(()=>blocks.value.find(i=>i.id===selectedId.value)??blocks.value[0]);const saving=ref(false),orderSaving=ref(false),saved=ref(false),uploading=ref(false),editorError=ref('');let timer:ReturnType<typeof setTimeout>|undefined
const palette:Array<{type:BlockType;label:string;description:string;icon:typeof Heading}>=[{type:'heading',label:'Заголовок',description:'Название раздела',icon:Heading},{type:'grammar',label:'Теория',description:'Правило и структура',icon:BookOpen},{type:'vocabulary',label:'Лексика',description:'Слова и примеры',icon:Languages},{type:'text',label:'Текст',description:'Объяснение',icon:Text},{type:'callout',label:'Формула',description:'Важная мысль',icon:MessageSquare},{type:'conversation',label:'Диалог',description:'Разговорная практика',icon:MessageCircle},{type:'audio',label:'Аудирование',description:'Файл, URL или озвучка',icon:Music2},{type:'flashcards',label:'Карточки',description:'Интервальное повторение',icon:Brain},{type:'error_correction',label:'Ошибки',description:'Разбор ошибок',icon:ShieldAlert},{type:'translation',label:'Перевод',description:'Language Engine',icon:Languages},{type:'practice',label:'Практика',description:'Активное задание',icon:Dumbbell},{type:'single_choice',label:'Вопрос теста',description:'4 варианта + разбор',icon:ListChecks}]
const labels:Record<BlockType,string>={heading:'Заголовок',grammar:'Теория',vocabulary:'Лексика',text:'Текст',callout:'Акцент',conversation:'Диалог',audio:'Аудирование',flashcards:'Карточки',error_correction:'Разбор ошибок',translation:'Перевод',practice:'Практика',single_choice:'Вопрос теста'}
async function add(type:BlockType){if(!found.value)return;await store.addBlock(found.value.lesson.id,type);selectedId.value=blocks.value.at(-1)?.id??''}
function scheduleSave(){saving.value=true;clearTimeout(timer);timer=setTimeout(async()=>{if(!found.value)return;try{await store.saveLesson(found.value.lesson.id);if(selected.value)await store.saveBlock(found.value.lesson.id,selected.value.id);saved.value=true;setTimeout(()=>saved.value=false,1200)}catch(e){editorError.value=e instanceof Error?e.message:'Не удалось сохранить'}finally{saving.value=false}},700)}
async function persistOrder(){if(!found.value)return;orderSaving.value=true;try{await store.persistBlockOrder(found.value.lesson.id);saved.value=true}catch(e){editorError.value=e instanceof Error?e.message:'Не удалось сохранить порядок'}finally{orderSaving.value=false}}
async function remove(){if(!found.value||!selected.value)return;await store.removeBlock(found.value.lesson.id,selected.value.id);selectedId.value=blocks.value[0]?.id??''}
async function publish(){if(!found.value)return;found.value.lesson.status='Опубликован';await store.saveLesson(found.value.lesson.id);saved.value=true}
function updateOptions(e:Event){if(!selected.value)return;selected.value.options=(e.target as HTMLTextAreaElement).value.split('\n').map(v=>v.trim()).filter(Boolean);if((selected.value.correctOption??0)>=selected.value.options.length)selected.value.correctOption=0;scheduleSave()}
async function upload(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file||!found.value||!selected.value)return;uploading.value=true;editorError.value='';try{await store.uploadAudio(found.value.lesson.id,selected.value.id,file);saved.value=true}catch(error){editorError.value=error instanceof Error?error.message:'Не удалось загрузить аудио'}finally{uploading.value=false;(e.target as HTMLInputElement).value=''}}
</script>
<template><div v-if="found" class="product-editor"><header class="product-editor-topbar"><RouterLink :to="`/app/courses/${found.course.id}`" class="editor-back"><ArrowLeft/></RouterLink><div class="editor-crumbs"><span>{{found.course.title}}</span><ChevronRight/><strong>{{found.lesson.title}}</strong></div><div class="editor-save-state"><span v-if="saving||orderSaving||uploading">Сохраняем…</span><span v-else-if="saved"><Check/>Сохранено</span></div><RouterLink :to="`/preview/lessons/${found.lesson.id}`" class="product-button product-button--secondary"><Eye/>Предпросмотр</RouterLink><UiButton @click="publish"><Save/>{{found.lesson.status==='Опубликован'?'Опубликовано':'Опубликовать'}}</UiButton></header>
<aside class="product-palette"><div class="editor-panel-title"><LayoutTemplate/><div><strong>Библиотека урока</strong><small>Теория, практика и контроль</small></div></div><div class="palette-list"><button v-for="item in palette" :key="item.type" @click="add(item.type)"><span><component :is="item.icon"/></span><div><strong>{{item.label}}</strong><small>{{item.description}}</small></div><Plus/></button></div><div class="palette-tip"><GripVertical/><p>Добавляйте несколько вопросов. Один блок теста — один вопрос.</p></div></aside>
<main class="product-canvas"><div v-if="editorError" class="product-alert is-error">{{editorError}}</div><div class="editor-document-head"><span>Урок · {{found.lesson.duration}} минут · {{blocks.filter(b=>b.type==='single_choice').length}} вопросов</span><input v-model="found.lesson.title" aria-label="Название урока" @input="scheduleSave"/><p>Сначала теория и примеры, затем аудирование и полноценная проверка.</p></div><VueDraggable v-model="blocks" item-key="id" handle=".block-drag-handle" :animation="180" ghost-class="drag-ghost" :force-fallback="true" chosen-class="drag-chosen" class="editor-block-list" @end="persistOrder"><article v-for="(item,index) in blocks" :key="item.id" :class="['product-editor-block',selected?.id===item.id&&'is-selected']" @click="selectedId=item.id"><button class="drag-handle block-drag-handle" aria-label="Переместить блок"><GripVertical/></button><div class="editor-block-number">{{String(index+1).padStart(2,'0')}}</div><div class="editor-block-content"><span>{{labels[item.type]}}</span><h2 v-if="item.type==='heading'">{{item.content}}</h2><p v-else-if="item.type==='text'">{{item.content}}</p><aside v-else-if="item.type==='callout'"><MessageSquare/><div><strong>{{item.title}}</strong><p>{{item.content}}</p></div></aside><section v-else-if="item.type==='grammar'||item.type==='vocabulary'" class="editor-theory"><component :is="item.type==='grammar'?BookOpen:Languages"/><div><strong>{{item.title}}</strong><p>{{item.content}}</p></div></section><LessonAudioPlayer v-else-if="item.type==='audio'" :src="item.audioUrl" :title="item.title" :transcript="item.transcript"/><section v-else-if="item.type==='conversation'||item.type==='flashcards'||item.type==='error_correction'||item.type==='translation'||item.type==='practice'" class="editor-theory"><component :is="item.type==='conversation'?MessageCircle:item.type==='flashcards'?Brain:item.type==='error_correction'?ShieldAlert:item.type==='translation'?Languages:Dumbbell"/><div><strong>{{item.title}}</strong><p>{{item.content}}</p></div></section><div v-else class="editor-question"><strong>{{item.content}}</strong><span v-for="(option,oi) in item.options" :key="`${option}-${oi}`" :class="oi===item.correctOption&&'is-correct'">{{String.fromCharCode(65+oi)}}. {{option}}</span><small v-if="item.explanation">Разбор: {{item.explanation}}</small></div></div></article></VueDraggable><button class="editor-insert" @click="add('text')"><Plus/>Добавить блок</button></main>
<aside class="product-inspector"><div class="editor-panel-title"><Settings2/><div><strong>Настройки</strong><small>{{selected?labels[selected.type]:'Блок не выбран'}}</small></div></div><template v-if="selected"><label>Название блока<input v-model="selected.title" @input="scheduleSave"/></label><label v-if="selected.type!=='audio'">Содержимое<textarea v-model="selected.content" @input="scheduleSave"></textarea></label><template v-if="selected.type==='audio'"><div class="audio-upload-zone"><Music2/><strong>{{selected.audioUrl?'Аудиозапись подключена':'Добавьте запись'}}</strong><small>MP3, M4A, OGG или WAV · до 50 МБ</small><label class="audio-upload-button"><Upload/>{{uploading?'Загрузка…':'Выбрать файл'}}<input type="file" accept="audio/mpeg,audio/mp4,audio/ogg,audio/wav" :disabled="uploading" @change="upload"/></label></div><label><Link/> Внешняя ссылка на аудио<input v-model="selected.audioUrl" placeholder="https://…/recording.mp3" @change="scheduleSave"/></label><label>Транскрипт для проверки и встроенной озвучки<textarea v-model="selected.transcript" class="large-textarea" placeholder="Paste the English transcript…" @input="scheduleSave"></textarea></label><small class="inspector-help">Если файл не загружен, транскрипт озвучивается браузером на английском. Загруженный файл всегда имеет приоритет.</small></template><template v-if="selected.type==='single_choice'"><label>Варианты ответа — каждый с новой строки<textarea :value="selected.options?.join('\n')" @input="updateOptions"></textarea></label><label>Правильный ответ<select v-model.number="selected.correctOption" @change="scheduleSave"><option v-for="(option,oi) in selected.options" :key="oi" :value="oi">{{String.fromCharCode(65+oi)}}. {{option}}</option></select></label><label>Объяснение ответа<textarea v-model="selected.explanation" placeholder="Почему этот вариант правильный?" @input="scheduleSave"></textarea></label></template><div class="inspector-row"><div><strong>Обязательный</strong><small>Нужен для завершения</small></div><UiSwitch v-model="selected.required" @update:model-value="scheduleSave"/></div><button class="inspector-delete" @click="remove"><Trash2/>Удалить блок</button></template></aside></div><section v-else class="product-empty full"><LayoutTemplate/><h2>Урок не найден</h2><RouterLink to="/app/courses" class="product-button">Вернуться к курсам</RouterLink></section></template>