-- ============================================================================
-- Course Platform: security, transactional commands and safe quiz verification
-- Apply this migration in Supabase SQL Editor AFTER a database backup.
--
-- Designed for the current owner/public production model:
-- - courses.owner_id identifies the author;
-- - published public courses can be viewed by guests;
-- - lesson_blocks.private_content must never be selected by learners;
-- - frontend mutations use the RPC functions declared below.
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- Storage cleanup outbox
-- PostgreSQL and Supabase Storage do not share one transaction. Destructive
-- RPCs enqueue file paths in the same DB transaction. The frontend removes the
-- objects only after the DB command succeeds and acknowledges successful paths.
-- ----------------------------------------------------------------------------

create table if not exists public.storage_cleanup_queue (
  id bigint generated by default as identity primary key,
  bucket_id text not null default 'lesson-assets',
  object_path text not null,
  requested_by uuid,
  status text not null default 'pending'
    check (status in ('pending', 'completed')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (bucket_id, object_path)
);

alter table public.storage_cleanup_queue
  add column if not exists requested_by uuid;

alter table public.storage_cleanup_queue enable row level security;
revoke all on table public.storage_cleanup_queue from anon, authenticated;

create index if not exists storage_cleanup_queue_pending_idx
  on public.storage_cleanup_queue(status, created_at)
  where status = 'pending';

create or replace function public.enqueue_lesson_assets(
  p_block_ids uuid[]
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.storage_cleanup_queue (
    bucket_id,
    object_path,
    requested_by,
    status,
    attempts,
    last_error,
    completed_at
  )
  select
    'lesson-assets',
    asset.object_path,
    auth.uid(),
    'pending',
    0,
    null,
    null
  from (
    select nullif(b.public_content ->> 'audioPath', '') as object_path
    from public.lesson_blocks b
    where b.id = any(coalesce(p_block_ids, array[]::uuid[]))

    union

    select nullif(b.public_content ->> 'filePath', '') as object_path
    from public.lesson_blocks b
    where b.id = any(coalesce(p_block_ids, array[]::uuid[]))
  ) asset
  where asset.object_path is not null
  on conflict (bucket_id, object_path)
  do update set
    requested_by = auth.uid(),
    status = 'pending',
    attempts = 0,
    last_error = null,
    completed_at = null;
$$;

revoke all on function public.enqueue_lesson_assets(uuid[]) from public;

create or replace function public.ack_storage_cleanup(
  p_paths text[]
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.storage_cleanup_queue
  set
    status = 'completed',
    completed_at = now(),
    last_error = null
  where bucket_id = 'lesson-assets'
    and requested_by = auth.uid()
    and object_path = any(coalesce(p_paths, array[]::text[]));
$$;

revoke all on function public.ack_storage_cleanup(text[]) from public;
grant execute on function public.ack_storage_cleanup(text[]) to authenticated;

-- ----------------------------------------------------------------------------
-- Course tree delivery
-- Direct learner SELECT on lesson_blocks is disabled below. This function
-- returns private_content only to the course owner.
-- ----------------------------------------------------------------------------

create or replace function public.build_course_tree_json(
  p_course_id uuid,
  p_include_private boolean
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select
    to_jsonb(c)
    || jsonb_build_object(
      'owner',
      coalesce(
        (
          select jsonb_build_object(
            'id', p.id,
            'display_name', p.display_name,
            'avatar_url', p.avatar_url
          )
          from public.profiles p
          where p.id = c.owner_id
        ),
        '{}'::jsonb
      ),
      'course_modules',
      coalesce(
        (
          select jsonb_agg(
            to_jsonb(m)
            || jsonb_build_object(
              'lessons',
              coalesce(
                (
                  select jsonb_agg(
                    to_jsonb(l)
                    || jsonb_build_object(
                      'lesson_blocks',
                      coalesce(
                        (
                          select jsonb_agg(
                            case
                              when p_include_private then to_jsonb(b)
                              else
                                (to_jsonb(b) - 'private_content')
                                || jsonb_build_object(
                                  'private_content',
                                  '{}'::jsonb
                                )
                            end
                            order by b.position, b.id
                          )
                          from public.lesson_blocks b
                          where b.lesson_id = l.id
                        ),
                        '[]'::jsonb
                      )
                    )
                    order by l.position, l.id
                  )
                  from public.lessons l
                  where l.module_id = m.id
                    and (
                      p_include_private
                      or l.status = 'published'
                    )
                ),
                '[]'::jsonb
              )
            )
            order by m.position, m.id
          )
          from public.course_modules m
          where m.course_id = c.id
            and (
              p_include_private
              or m.is_published
            )
        ),
        '[]'::jsonb
      )
    )
  from public.courses c
  where c.id = p_course_id;
$$;

revoke all on function public.build_course_tree_json(uuid, boolean)
  from public;

create or replace function public.get_course_tree(
  p_course_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_owner_id uuid;
  v_status text;
  v_visibility text;
  v_include_private boolean;
begin
  select
    c.owner_id,
    c.status::text,
    c.visibility::text
  into
    v_owner_id,
    v_status,
    v_visibility
  from public.courses c
  where c.id = p_course_id;

  if not found then
    return null;
  end if;

  v_include_private := auth.uid() is not null
    and auth.uid() = v_owner_id;

  if not v_include_private
    and not (
      v_status = 'published'
      and v_visibility in ('public', 'unlisted')
    )
  then
    raise exception 'course_not_accessible'
      using errcode = '42501';
  end if;

  return public.build_course_tree_json(
    p_course_id,
    v_include_private
  );
end;
$$;

revoke all on function public.get_course_tree(uuid) from public;
grant execute on function public.get_course_tree(uuid)
  to anon, authenticated;

-- ----------------------------------------------------------------------------
-- Quiz verification
-- The correct option and author explanation remain server-side.
-- ----------------------------------------------------------------------------

create or replace function public.check_lesson_block_answer(
  p_block_id uuid,
  p_option_index integer
)
returns table (
  correct boolean,
  explanation text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_course_id uuid;
  v_lesson_status text;
  v_course_status text;
  v_visibility text;
  v_owner_id uuid;
  v_correct_option integer;
  v_explanation text;
begin
  select
    b.course_id,
    l.status::text,
    c.status::text,
    c.visibility::text,
    c.owner_id,
    case
      when jsonb_typeof(b.private_content -> 'correctOption') = 'number'
      then (b.private_content ->> 'correctOption')::integer
      else null
    end,
    coalesce(b.private_content ->> 'explanation', '')
  into
    v_course_id,
    v_lesson_status,
    v_course_status,
    v_visibility,
    v_owner_id,
    v_correct_option,
    v_explanation
  from public.lesson_blocks b
  join public.lessons l on l.id = b.lesson_id
  join public.courses c on c.id = b.course_id
  where b.id = p_block_id
    and b.block_type = 'single_choice';

  if not found then
    raise exception 'quiz_block_not_found'
      using errcode = 'P0002';
  end if;

  if not (
    coalesce(auth.uid() = v_owner_id, false)
    or (
      v_course_status = 'published'
      and v_lesson_status = 'published'
      and v_visibility in ('public', 'unlisted')
    )
  )
  then
    raise exception 'quiz_block_not_accessible'
      using errcode = '42501';
  end if;

  return query
  select
    coalesce(p_option_index = v_correct_option, false),
    v_explanation;
end;
$$;

revoke all on function public.check_lesson_block_answer(uuid, integer)
  from public;
grant execute on function public.check_lesson_block_answer(uuid, integer)
  to anon, authenticated;

-- ----------------------------------------------------------------------------
-- Transactional publication commands
-- ----------------------------------------------------------------------------

create or replace function public.publish_course(
  p_course_id uuid,
  p_changelog text default 'Published from Course Platform'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_course public.courses%rowtype;
  v_release_id uuid;
  v_version integer;
  v_published_at timestamptz := now();
  v_module_count integer;
  v_lesson_count integer;
  v_snapshot jsonb;
begin
  if auth.uid() is null then
    raise exception 'authentication_required'
      using errcode = '42501';
  end if;

  select *
  into v_course
  from public.courses
  where id = p_course_id
  for update;

  if not found then
    raise exception 'course_not_found'
      using errcode = 'P0002';
  end if;

  if v_course.owner_id <> auth.uid() then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  update public.lessons
  set
    status = 'published',
    published_at = v_published_at,
    updated_at = v_published_at
  where course_id = p_course_id;

  update public.course_modules
  set
    is_published = true,
    updated_at = v_published_at
  where course_id = p_course_id;

  update public.courses
  set
    status = 'published',
    visibility = 'public',
    published_at = v_published_at,
    updated_at = v_published_at
  where id = p_course_id;

  select coalesce(max(r.version), 0) + 1
  into v_version
  from public.course_releases r
  where r.course_id = p_course_id;

  select count(*)
  into v_module_count
  from public.course_modules
  where course_id = p_course_id;

  select count(*)
  into v_lesson_count
  from public.lessons
  where course_id = p_course_id;

  v_snapshot := jsonb_build_object(
    'schemaVersion', 1,
    'publishedAt', v_published_at,
    'course', public.build_course_tree_json(
      p_course_id,
      false
    )
  );

  insert into public.course_releases (
    course_id,
    version,
    snapshot,
    module_count,
    lesson_count,
    changelog,
    published_by,
    published_at
  )
  values (
    p_course_id,
    v_version,
    v_snapshot,
    v_module_count,
    v_lesson_count,
    nullif(trim(coalesce(p_changelog, '')), ''),
    auth.uid(),
    v_published_at
  )
  returning id into v_release_id;

  update public.courses
  set current_release_id = v_release_id
  where id = p_course_id;

  return v_release_id;
end;
$$;

revoke all on function public.publish_course(uuid, text) from public;
grant execute on function public.publish_course(uuid, text)
  to authenticated;

create or replace function public.draft_course(
  p_course_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid;
begin
  select owner_id
  into v_owner_id
  from public.courses
  where id = p_course_id
  for update;

  if not found then
    raise exception 'course_not_found'
      using errcode = 'P0002';
  end if;

  if v_owner_id <> auth.uid() then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  update public.lessons
  set
    status = 'draft',
    published_at = null,
    updated_at = now()
  where course_id = p_course_id;

  update public.course_modules
  set
    is_published = false,
    updated_at = now()
  where course_id = p_course_id;

  update public.courses
  set
    status = 'draft',
    visibility = 'private',
    current_release_id = null,
    published_at = null,
    updated_at = now()
  where id = p_course_id;
end;
$$;

revoke all on function public.draft_course(uuid) from public;
grant execute on function public.draft_course(uuid)
  to authenticated;

-- ----------------------------------------------------------------------------
-- Transactional ordering
-- ----------------------------------------------------------------------------

create or replace function public.reorder_course_tree(
  p_course_id uuid,
  p_modules jsonb,
  p_lessons jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1
  from public.courses
  where id = p_course_id
    and owner_id = auth.uid()
  for update;

  if not found then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(
      coalesce(p_modules, '[]'::jsonb)
    ) as item(id uuid, position integer)
    where not exists (
      select 1
      from public.course_modules m
      where m.id = item.id
        and m.course_id = p_course_id
    )
  ) then
    raise exception 'invalid_module_order_payload'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(
      coalesce(p_lessons, '[]'::jsonb)
    ) as item(id uuid, module_id uuid, position integer)
    where not exists (
      select 1
      from public.lessons l
      join public.course_modules m
        on m.id = item.module_id
       and m.course_id = p_course_id
      where l.id = item.id
        and l.course_id = p_course_id
    )
  ) then
    raise exception 'invalid_lesson_order_payload'
      using errcode = '22023';
  end if;

  update public.course_modules m
  set
    position = item.position,
    updated_at = now()
  from jsonb_to_recordset(
    coalesce(p_modules, '[]'::jsonb)
  ) as item(id uuid, position integer)
  where m.id = item.id
    and m.course_id = p_course_id;

  update public.lessons l
  set
    module_id = item.module_id,
    position = item.position,
    updated_at = now()
  from jsonb_to_recordset(
    coalesce(p_lessons, '[]'::jsonb)
  ) as item(id uuid, module_id uuid, position integer)
  where l.id = item.id
    and l.course_id = p_course_id;
end;
$$;

revoke all on function public.reorder_course_tree(uuid, jsonb, jsonb)
  from public;
grant execute on function public.reorder_course_tree(uuid, jsonb, jsonb)
  to authenticated;

drop function if exists public.reorder_lesson_blocks(uuid, jsonb);

create or replace function public.reorder_lesson_blocks(
  p_lesson_id uuid,
  p_blocks jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_course_id uuid;
begin
  select course_id
  into v_course_id
  from public.lessons
  where id = p_lesson_id;

  if not found
    or not public.can_manage_course(v_course_id)
  then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  perform 1
  from public.courses
  where id = v_course_id
  for update;

  if exists (
    select 1
    from jsonb_to_recordset(
      coalesce(p_blocks, '[]'::jsonb)
    ) as item(id uuid, position integer)
    where not exists (
      select 1
      from public.lesson_blocks b
      where b.id = item.id
        and b.lesson_id = p_lesson_id
    )
  ) then
    raise exception 'invalid_block_order_payload'
      using errcode = '22023';
  end if;

  update public.lesson_blocks b
  set
    position = item.position,
    updated_at = now()
  from jsonb_to_recordset(
    coalesce(p_blocks, '[]'::jsonb)
  ) as item(id uuid, position integer)
  where b.id = item.id
    and b.lesson_id = p_lesson_id;
end;
$$;

revoke all on function public.reorder_lesson_blocks(uuid, jsonb)
  from public;
grant execute on function public.reorder_lesson_blocks(uuid, jsonb)
  to authenticated;

-- ----------------------------------------------------------------------------
-- Transactional duplication
-- ----------------------------------------------------------------------------

create or replace function public.duplicate_lesson(
  p_lesson_id uuid,
  p_target_module_id uuid,
  p_position integer,
  p_title text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.lessons%rowtype;
  v_course_id uuid;
  v_new_lesson_id uuid;
begin
  select *
  into v_source
  from public.lessons
  where id = p_lesson_id;

  if not found then
    raise exception 'lesson_not_found'
      using errcode = 'P0002';
  end if;

  v_course_id := v_source.course_id;

  perform 1
  from public.courses
  where id = v_course_id
    and owner_id = auth.uid()
  for update;

  if not found then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.course_modules
    where id = p_target_module_id
      and course_id = v_course_id
  ) then
    raise exception 'target_module_not_found'
      using errcode = '22023';
  end if;

  update public.lessons
  set position = position + 1
  where module_id = p_target_module_id
    and position >= greatest(p_position, 0);

  insert into public.lessons (
    course_id,
    module_id,
    slug,
    title,
    description,
    objectives,
    duration_minutes,
    passing_score,
    position,
    status,
    is_preview
  )
  values (
    v_course_id,
    p_target_module_id,
    'lesson-' || replace(gen_random_uuid()::text, '-', ''),
    coalesce(nullif(trim(p_title), ''), v_source.title || ' — копия'),
    v_source.description,
    v_source.objectives,
    v_source.duration_minutes,
    v_source.passing_score,
    greatest(p_position, 0),
    'draft',
    false
  )
  returning id into v_new_lesson_id;

  insert into public.lesson_blocks (
    course_id,
    lesson_id,
    block_type,
    position,
    title,
    public_content,
    private_content,
    settings,
    is_required,
    points,
    schema_version
  )
  select
    v_course_id,
    v_new_lesson_id,
    b.block_type,
    b.position,
    b.title,
    b.public_content
      - 'audioPath'
      - 'filePath'
      - 'fileName'
      - 'fileSize',
    b.private_content,
    b.settings,
    b.is_required,
    b.points,
    b.schema_version
  from public.lesson_blocks b
  where b.lesson_id = p_lesson_id
  order by b.position, b.id;

  return v_new_lesson_id;
end;
$$;

revoke all on function public.duplicate_lesson(uuid, uuid, integer, text)
  from public;
grant execute on function public.duplicate_lesson(uuid, uuid, integer, text)
  to authenticated;

create or replace function public.duplicate_module(
  p_module_id uuid,
  p_position integer,
  p_title text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.course_modules%rowtype;
  v_new_module_id uuid;
  v_source_lesson public.lessons%rowtype;
  v_new_lesson_id uuid;
begin
  select *
  into v_source
  from public.course_modules
  where id = p_module_id;

  if not found then
    raise exception 'module_not_found'
      using errcode = 'P0002';
  end if;

  perform 1
  from public.courses
  where id = v_source.course_id
    and owner_id = auth.uid()
  for update;

  if not found then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  update public.course_modules
  set position = position + 1
  where course_id = v_source.course_id
    and position >= greatest(p_position, 0);

  insert into public.course_modules (
    course_id,
    title,
    description,
    position,
    is_published
  )
  values (
    v_source.course_id,
    coalesce(nullif(trim(p_title), ''), v_source.title || ' — копия'),
    v_source.description,
    greatest(p_position, 0),
    false
  )
  returning id into v_new_module_id;

  for v_source_lesson in
    select *
    from public.lessons
    where module_id = p_module_id
    order by position, id
  loop
    insert into public.lessons (
      course_id,
      module_id,
      slug,
      title,
      description,
      objectives,
      duration_minutes,
      passing_score,
      position,
      status,
      is_preview
    )
    values (
      v_source.course_id,
      v_new_module_id,
      'lesson-' || replace(gen_random_uuid()::text, '-', ''),
      v_source_lesson.title,
      v_source_lesson.description,
      v_source_lesson.objectives,
      v_source_lesson.duration_minutes,
      v_source_lesson.passing_score,
      v_source_lesson.position,
      'draft',
      false
    )
    returning id into v_new_lesson_id;

    insert into public.lesson_blocks (
      course_id,
      lesson_id,
      block_type,
      position,
      title,
      public_content,
      private_content,
      settings,
      is_required,
      points,
      schema_version
    )
    select
      v_source.course_id,
      v_new_lesson_id,
      b.block_type,
      b.position,
      b.title,
      b.public_content
        - 'audioPath'
        - 'filePath'
        - 'fileName'
        - 'fileSize',
      b.private_content,
      b.settings,
      b.is_required,
      b.points,
      b.schema_version
    from public.lesson_blocks b
    where b.lesson_id = v_source_lesson.id
    order by b.position, b.id;
  end loop;

  return v_new_module_id;
end;
$$;

revoke all on function public.duplicate_module(uuid, integer, text)
  from public;
grant execute on function public.duplicate_module(uuid, integer, text)
  to authenticated;

-- ----------------------------------------------------------------------------
-- Transactional deletion
-- ----------------------------------------------------------------------------

create or replace function public.delete_lesson_block(
  p_block_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_course_id uuid;
begin
  select course_id
  into v_course_id
  from public.lesson_blocks
  where id = p_block_id
  for update;

  if not found
    or not public.can_manage_course(v_course_id)
  then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  perform public.enqueue_lesson_assets(array[p_block_id]);

  delete from public.lesson_blocks
  where id = p_block_id;
end;
$$;

revoke all on function public.delete_lesson_block(uuid) from public;
grant execute on function public.delete_lesson_block(uuid)
  to authenticated;

create or replace function public.delete_lessons(
  p_course_id uuid,
  p_lesson_ids uuid[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_block_ids uuid[];
begin
  perform 1
  from public.courses
  where id = p_course_id
    and owner_id = auth.uid()
  for update;

  if not found then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  if exists (
    select 1
    from unnest(
      coalesce(p_lesson_ids, array[]::uuid[])
    ) as item(lesson_id)
    where not exists (
      select 1
      from public.lessons l
      where l.id = item.lesson_id
        and l.course_id = p_course_id
    )
  ) then
    raise exception 'invalid_lesson_delete_payload'
      using errcode = '22023';
  end if;

  select coalesce(array_agg(b.id), array[]::uuid[])
  into v_block_ids
  from public.lesson_blocks b
  where b.lesson_id = any(
    coalesce(p_lesson_ids, array[]::uuid[])
  );

  perform public.enqueue_lesson_assets(v_block_ids);

  delete from public.lessons
  where course_id = p_course_id
    and id = any(coalesce(p_lesson_ids, array[]::uuid[]));
end;
$$;

revoke all on function public.delete_lessons(uuid, uuid[]) from public;
grant execute on function public.delete_lessons(uuid, uuid[])
  to authenticated;

create or replace function public.delete_course(
  p_course_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_block_ids uuid[];
begin
  perform 1
  from public.courses
  where id = p_course_id
    and owner_id = auth.uid()
  for update;

  if not found then
    raise exception 'course_owner_required'
      using errcode = '42501';
  end if;

  select coalesce(array_agg(b.id), array[]::uuid[])
  into v_block_ids
  from public.lesson_blocks b
  where b.course_id = p_course_id;

  perform public.enqueue_lesson_assets(v_block_ids);

  update public.courses
  set current_release_id = null
  where id = p_course_id;

  delete from public.courses
  where id = p_course_id;
end;
$$;

revoke all on function public.delete_course(uuid) from public;
grant execute on function public.delete_course(uuid)
  to authenticated;

-- ----------------------------------------------------------------------------
-- Close the private-content leak.
--
-- Learners no longer SELECT lesson_blocks directly. Owners retain direct SELECT
-- for authoring operations. Public/learner delivery goes through get_course_tree.
-- Releases are also owner-only because historical snapshots can contain legacy
-- private data created before this migration.
-- ----------------------------------------------------------------------------

alter table public.lesson_blocks enable row level security;
alter table public.course_releases enable row level security;

revoke select on table public.lesson_blocks from anon;
revoke select on table public.course_releases from anon;

grant select, insert, update, delete
  on table public.lesson_blocks
  to authenticated;

grant select, insert, update, delete
  on table public.course_releases
  to authenticated;

drop policy if exists lesson_blocks_select_author
  on public.lesson_blocks;
drop policy if exists lesson_blocks_select_accessible
  on public.lesson_blocks;
drop policy if exists lesson_blocks_select_owner
  on public.lesson_blocks;

create policy lesson_blocks_select_owner
on public.lesson_blocks
for select
to authenticated
using (public.can_manage_course(course_id));

drop policy if exists releases_select_author
  on public.course_releases;
drop policy if exists releases_select_accessible
  on public.course_releases;
drop policy if exists releases_select_owner
  on public.course_releases;

create policy releases_select_owner
on public.course_releases
for select
to authenticated
using (public.can_manage_course(course_id));

commit;
