import { computed, ref, watch } from 'vue'
import { defineStore } from 'pinia'
import type { BlockType, Course, Learner, LessonBlock } from '@/types/course'
import { isSupabaseConfigured, requireSupabase } from '@/services/supabase'
import { useAuthStore } from '@/stores/auth'
import { slugify } from '@/utils/slugify'
import { seedEnglishB2Course } from '@/services/seed-english-course'

const block = (id:string,type:BlockType,title:string,content:string,extra:Partial<LessonBlock>={}):LessonBlock => ({id,type,title,content,required:true,...extra})
const seedCourses:Course[]=[
{id:'chinese',title:'Китайский язык: с нуля до HSK 1',description:'Базовая грамматика, иероглифы и разговорная практика',cover:'linear-gradient(135deg,#7a3026,#d56956)',tag:'中文',status:'Опубликован',students:128,progress:76,updated:'Сегодня',modules:[
{id:'m1',title:'Основы китайского языка',open:true,lessons:[{id:'greetings',title:'Знакомство и приветствия',duration:15,status:'Опубликован',blocks:[block('b1','heading','Заголовок','Знакомство и приветствия'),block('b2','text','Текст','В этом уроке вы научитесь здороваться и представляться на китайском языке.'),block('b3','callout','Запомните','你好 (nǐ hǎo) — здравствуйте. 谢谢 (xièxie) — спасибо.'),block('b4','audio','Аудио','Приветствие — диалог двух собеседников'),block('b5','single_choice','Один вариант','Как сказать «Здравствуйте» по-китайски?',{options:['你好 (nǐ hǎo)','谢谢 (xièxie)','再见 (zàijiàn)'],correctOption:0})]},{id:'tones',title:'Китайская фонетика: четыре тона',duration:20,status:'Черновик',blocks:[block('b6','heading','Заголовок','Четыре тона китайского языка'),block('b7','text','Текст','Тон меняет значение слога. Послушайте и повторите каждый пример.')]},{id:'characters',title:'Первые иероглифы',duration:18,status:'Черновик',blocks:[block('b8','heading','Заголовок','Первые иероглифы')]}]},
{id:'m2',title:'Числа, время и повседневность',open:true,lessons:[{id:'numbers',title:'Числа от 1 до 100',duration:15,status:'Черновик',blocks:[block('b9','heading','Заголовок','Числа от 1 до 100')]},{id:'time',title:'Как спросить время',duration:15,status:'Черновик',blocks:[]},{id:'day',title:'Мой обычный день',duration:20,status:'Черновик',blocks:[]}]},
{id:'m3',title:'Семья и окружение',open:false,lessons:[{id:'family',title:'Члены семьи',duration:15,status:'Черновик',blocks:[]},{id:'person',title:'Описание человека',duration:18,status:'Черновик',blocks:[]}]}]},
{id:'english',title:'Business English',description:'Деловая переписка, встречи и презентации',cover:'linear-gradient(135deg,#173e6b,#4382bd)',tag:'EN',status:'Опубликован',students:64,progress:62,updated:'Вчера',modules:[{id:'em1',title:'Business communication',open:true,lessons:[{id:'emails',title:'Professional emails',duration:25,status:'Опубликован',blocks:[block('eb1','heading','Heading','Professional emails'),block('eb2','text','Text','Learn to write concise and polite business emails.')]}]}]},
{id:'design',title:'Основы продуктового дизайна',description:'От исследования задачи до готового прототипа',cover:'linear-gradient(135deg,#3e2467,#9567c1)',tag:'✦',status:'Черновик',students:0,progress:35,updated:'3 дня назад',modules:[]}
]
const seedLearners:Learner[]=[{id:'l1',name:'Анна Крылова',email:'anna@example.com',course:'Китайский язык: с нуля до HSK 1',progress:84,status:'Активен'},{id:'l2',name:'Михаил Соколов',email:'mikhail@example.com',course:'Business English',progress:62,status:'Активен'},{id:'l3',name:'Елена Волкова',email:'elena@example.com',course:'Китайский язык: с нуля до HSK 1',progress:100,status:'Завершил'}]

export const useCourseStore=defineStore('courses',()=>{
 const saved=localStorage.getItem('cursor-courses'); const courses=ref<Course[]>(isSupabaseConfigured?[]:(saved?JSON.parse(saved):seedCourses)); const learners=ref<Learner[]>(isSupabaseConfigured?[]:seedLearners); const loading=ref(false); const loadError=ref('')
 if(!isSupabaseConfigured)watch(courses,value=>localStorage.setItem('cursor-courses',JSON.stringify(value)),{deep:true})
 const totalLessons=computed(()=>courses.value.reduce((sum,c)=>sum+c.modules.reduce((s,m)=>s+m.lessons.length,0),0))
 const findCourse=(id:string)=>courses.value.find(c=>c.id===id)
 const findLesson=(id:string)=>{for(const course of courses.value)for(const module of course.modules){const lesson=module.lessons.find(l=>l.id===id);if(lesson)return{course,module,lesson}}}
 async function hydrate(){
  if(!isSupabaseConfigured)return
  const auth=useAuthStore();loading.value=true;loadError.value=''
  try{if(!auth.organization)await auth.loadOrganization();if(!auth.organization||!auth.user){courses.value=[];return}
   await seedEnglishB2Course(auth.organization.id,auth.user.id)
   const{data,error}=await requireSupabase().from('courses').select('id,title,description,status,accent_color,updated_at,course_modules(id,title,position,lessons(id,title,duration_minutes,status,position,lesson_blocks(id,block_type,title,public_content,private_content,is_required,position)))').eq('organization_id',auth.organization.id).order('updated_at',{ascending:false});if(error)throw error
   courses.value=((data??[])as unknown as Array<Record<string,unknown>>).map(mapDbCourse)
   const{data:enrollments,error:enrollmentsError}=await requireSupabase().from('course_enrollments').select('id,status,progress_percent,learners(id,display_name,email),courses(title)');if(!enrollmentsError)learners.value=((enrollments??[])as unknown as Array<Record<string,unknown>>).map(row=>{const learner=row.learners as Record<string,unknown>;const course=row.courses as Record<string,unknown>;return{id:String(learner.id),name:String(learner.display_name??learner.email??'Ученик'),email:String(learner.email??''),course:String(course.title??''),progress:Number(row.progress_percent),status:row.status==='completed'?'Завершил':'Активен'}})
  }catch(error){loadError.value=error instanceof Error?error.message:'Не удалось загрузить данные'}finally{loading.value=false}
 }
 function mapDbCourse(row:Record<string,unknown>):Course{
  const modules=((row.course_modules??[])as Array<Record<string,unknown>>).sort((a,b)=>Number(a.position)-Number(b.position)).map(module=>({id:String(module.id),title:String(module.title),open:true,lessons:((module.lessons??[])as Array<Record<string,unknown>>).sort((a,b)=>Number(a.position)-Number(b.position)).map(lesson=>({id:String(lesson.id),title:String(lesson.title),duration:Number(lesson.duration_minutes),status:lesson.status==='published'?'Опубликован' as const:'Черновик' as const,blocks:((lesson.lesson_blocks??[])as Array<Record<string,unknown>>).sort((a,b)=>Number(a.position)-Number(b.position)).map(item=>{const pub=(item.public_content??{})as Record<string,unknown>;const priv=(item.private_content??{})as Record<string,unknown>;return{id:String(item.id),type:item.block_type==='rich_text'?'text':String(item.block_type) as BlockType,title:String(item.title??''),content:String(pub.content??pub.text??pub.question??''),required:Boolean(item.is_required),options:Array.isArray(pub.options)?pub.options.map(option=>typeof option==='string'?option:String((option as Record<string,unknown>).label??'')):undefined,correctOption:typeof priv.correctOption==='number'?priv.correctOption:undefined}})}))}))
  return{id:String(row.id),title:String(row.title),description:String(row.description??''),cover:`linear-gradient(135deg,${String(row.accent_color??'#7a3026')},#d98b77)`,tag:String(row.title).slice(0,2).toUpperCase(),status:row.status==='published'?'Опубликован':'Черновик',students:0,progress:0,updated:new Date(String(row.updated_at)).toLocaleDateString('ru-RU'),modules}
 }
 async function createCourse(title:string,description:string){
  if(!isSupabaseConfigured){const id=`course-${Date.now()}`;courses.value.unshift({id,title,description,cover:'linear-gradient(135deg,#b9533d,#ef9274)',tag:title.slice(0,2).toUpperCase(),status:'Черновик',students:0,progress:0,updated:'Только что',modules:[]});return id}
  const auth=useAuthStore();if(!auth.organization||!auth.user)throw new Error('Организация пользователя не найдена')
  const slug=slugify(title,'course')
  const{data,error}=await requireSupabase().from('courses').insert({organization_id:auth.organization.id,owner_id:auth.user.id,title,description,slug,language_code:'ru'}).select('id').single();if(error)throw error;await hydrate();return String(data.id)
 }
 async function addModule(courseId:string,title='Новый модуль'){const course=findCourse(courseId);if(!course)return;if(!isSupabaseConfigured){course.modules.push({id:`module-${Date.now()}`,title,open:true,lessons:[]});return}const{error}=await requireSupabase().from('course_modules').insert({course_id:courseId,title,position:course.modules.length});if(error)throw error;await hydrate()}
 async function addLesson(courseId:string,moduleId:string,title='Новый урок'){const module=findCourse(courseId)?.modules.find(m=>m.id===moduleId);if(!module)return;if(!isSupabaseConfigured){const id=`lesson-${Date.now()}`;module.lessons.push({id,title,duration:15,status:'Черновик',blocks:[]});return id}const slug=slugify(title,'lesson');const{data,error}=await requireSupabase().from('lessons').insert({course_id:courseId,module_id:moduleId,title,slug,duration_minutes:15,position:module.lessons.length}).select('id').single();if(error)throw error;await hydrate();return String(data.id)}
 async function addBlock(lessonId:string,type:BlockType){const found=findLesson(lessonId);if(!found)return;const defaults:Record<BlockType,[string,string]>={heading:['Заголовок','Новый заголовок'],text:['Текст','Начните писать текст урока…'],callout:['Важное','Добавьте важную мысль'],audio:['Аудио','Аудиоматериал'],single_choice:['Один вариант','Введите вопрос']};const [title,content]=defaults[type];const extra=type==='single_choice'?{options:['Вариант 1','Вариант 2'],correctOption:0}:{};if(!isSupabaseConfigured){found.lesson.blocks.push(block(`block-${Date.now()}`,type,title,content,extra));return}const publicContent=type==='single_choice'?{question:content,options:['Вариант 1','Вариант 2'].map((label,index)=>({id:String(index),label}))}:{content};const privateContent=type==='single_choice'?{correctOption:0}:{};const{error}=await requireSupabase().from('lesson_blocks').insert({course_id:found.course.id,lesson_id:lessonId,block_type:type==='text'?'rich_text':type,title,public_content:publicContent,private_content:privateContent,position:found.lesson.blocks.length});if(error)throw error;await hydrate()}
 async function saveLesson(lessonId:string){const found=findLesson(lessonId);if(!found||!isSupabaseConfigured)return;const{error}=await requireSupabase().from('lessons').update({title:found.lesson.title,duration_minutes:found.lesson.duration,status:found.lesson.status==='Опубликован'?'published':'draft'}).eq('id',lessonId);if(error)throw error}
 async function saveBlock(lessonId:string,blockId:string){if(!isSupabaseConfigured)return;const found=findLesson(lessonId);const item=found?.lesson.blocks.find(b=>b.id===blockId);if(!item)return;const publicContent=item.type==='single_choice'?{question:item.content,options:item.options?.map((label,index)=>({id:String(index),label}))}:{content:item.content};const privateContent=item.type==='single_choice'?{correctOption:item.correctOption??0}:{};const{error}=await requireSupabase().from('lesson_blocks').update({title:item.title,public_content:publicContent,private_content:privateContent,is_required:item.required}).eq('id',blockId);if(error)loadError.value=error.message}
 async function removeBlock(lessonId:string,blockId:string){const found=findLesson(lessonId);if(found)found.lesson.blocks=found.lesson.blocks.filter(b=>b.id!==blockId);if(isSupabaseConfigured){const{error}=await requireSupabase().from('lesson_blocks').delete().eq('id',blockId);if(error)throw error}}
 async function saveCourse(courseId:string){const course=findCourse(courseId);if(!course||!isSupabaseConfigured)return;const{error}=await requireSupabase().from('courses').update({title:course.title,description:course.description}).eq('id',courseId);if(error)throw error;course.updated='Только что'}
 async function publishCourse(id:string){if(!isSupabaseConfigured){const c=findCourse(id);if(c){c.status='Опубликован';c.updated='Только что'};return}const{error}=await requireSupabase().rpc('publish_course',{p_course_id:id,p_changelog:'Published from Course Platform'});if(error)throw error;await hydrate()}
 async function persistCourseOrder(courseId:string){
  const course=findCourse(courseId);if(!course||!isSupabaseConfigured)return
  try{
   await Promise.all(course.modules.map((module,position)=>requireSupabase().from('course_modules').update({position}).eq('id',module.id).then(({error})=>{if(error)throw error})))
   await Promise.all(course.modules.flatMap(module=>module.lessons.map((lesson,position)=>requireSupabase().from('lessons').update({module_id:module.id,position}).eq('id',lesson.id).then(({error})=>{if(error)throw error}))))
  }catch(error){loadError.value=error instanceof Error?error.message:'Не удалось сохранить порядок';await hydrate();throw error}
 }
 async function persistBlockOrder(lessonId:string){
  const found=findLesson(lessonId);if(!found||!isSupabaseConfigured)return
  try{await Promise.all(found.lesson.blocks.map((item,position)=>requireSupabase().from('lesson_blocks').update({position}).eq('id',item.id).then(({error})=>{if(error)throw error})))}catch(error){loadError.value=error instanceof Error?error.message:'Не удалось сохранить порядок блоков';await hydrate();throw error}
 }
 function resetDemo(){if(!isSupabaseConfigured)courses.value=structuredClone(seedCourses)}
 return{courses,learners,loading,loadError,totalLessons,findCourse,findLesson,hydrate,createCourse,addModule,addLesson,addBlock,saveLesson,saveBlock,removeBlock,saveCourse,publishCourse,persistCourseOrder,persistBlockOrder,resetDemo}
})