import{computed,ref,watch}from'vue'
import{defineStore}from'pinia'
import type{BlockType,CorrectionItem,Course,Flashcard,Learner,LessonBlock}from'@/types/course'
import{isSupabaseConfigured,requireSupabase}from'@/services/supabase'
import{useAuthStore}from'@/stores/auth'
import{slugify}from'@/utils/slugify'
import{buildEnglishEngineDemoCourse,seedEnglishEngineCourse}from'@/services/seed-english-engine'
import{createLessonAudioUrl,uploadLessonAudio}from'@/services/lesson-audio.service'
const makeBlock=(id:string,type:BlockType,title:string,content:string,extra:Partial<LessonBlock>={}):LessonBlock=>({id,type,title,content,required:true,...extra})
const demoCourses:Course[]=[buildEnglishEngineDemoCourse()]
const dbType=(type:BlockType)=>({text:'rich_text',conversation:'open_answer',error_correction:'grammar',practice:'homework'}as Partial<Record<BlockType,string>>)[type]??type
export const useCourseStore=defineStore('courses',()=>{const saved=localStorage.getItem('cursor-courses-v3');const courses=ref<Course[]>(isSupabaseConfigured?[]:(saved?JSON.parse(saved):demoCourses));const learners=ref<Learner[]>([]);const loading=ref(false),loadError=ref('');if(!isSupabaseConfigured)watch(courses,value=>localStorage.setItem('cursor-courses-v3',JSON.stringify(value)),{deep:true});const totalLessons=computed(()=>courses.value.reduce((sum,c)=>sum+c.modules.reduce((s,m)=>s+m.lessons.length,0),0));const findCourse=(id:string)=>courses.value.find(course=>course.id===id);const findLesson=(id:string)=>{for(const course of courses.value)for(const module of course.modules){const lesson=module.lessons.find(item=>item.id===id);if(lesson)return{course,module,lesson}}}
function mapBlock(item:Record<string,unknown>):LessonBlock{const pub=(item.public_content??{})as Record<string,unknown>,priv=(item.private_content??{})as Record<string,unknown>,kind=String(pub.kind??'');const rawType=String(item.block_type);const type:BlockType=rawType==='rich_text'?'text':rawType==='open_answer'&&kind==='conversation'?'conversation':rawType==='grammar'&&kind==='error_correction'?'error_correction':rawType==='homework'?'practice':rawType as BlockType;const cards=Array.isArray(pub.cards)?pub.cards.map(card=>{const value=card as Record<string,unknown>;return{front:String(value.front??''),back:String(value.back??''),hint:String(value.hint??'')}}):undefined;const corrections=Array.isArray(pub.items)?pub.items.map(row=>{const value=row as Record<string,unknown>;return{incorrect:String(value.incorrect??''),correct:String(value.correct??''),explanation:String(value.explanation??'')}}):undefined;return{id:String(item.id),type,title:String(item.title??''),content:String(pub.content??pub.text??pub.question??''),required:Boolean(item.is_required),options:Array.isArray(pub.options)?pub.options.map(option=>typeof option==='string'?option:String((option as Record<string,unknown>).label??'')):undefined,correctOption:typeof priv.correctOption==='number'?priv.correctOption:undefined,explanation:String(priv.explanation??''),audioPath:String(pub.audioPath??''),audioUrl:String(pub.audioUrl??''),transcript:String(pub.transcript??''),cards,role:String(pub.role??''),prompt:String(pub.prompt??''),starter:String(pub.starter??''),sampleAnswer:String(pub.sampleAnswer??''),corrections,sourceText:String(pub.sourceText??''),targetText:String(priv.targetText??''),comprehensionQuestions:Array.isArray(pub.questions)?pub.questions.map(String):undefined}}
function mapDbCourse(row:Record<string,unknown>):Course{const modules=((row.course_modules??[])as Record<string,unknown>[]).sort((a,b)=>Number(a.position)-Number(b.position)).map(module=>({id:String(module.id),title:String(module.title),open:true,lessons:((module.lessons??[])as Record<string,unknown>[]).sort((a,b)=>Number(a.position)-Number(b.position)).map(lesson=>({id:String(lesson.id),title:String(lesson.title),duration:Number(lesson.duration_minutes),status:lesson.status==='published'?'Опубликован' as const:'Черновик' as const,blocks:((lesson.lesson_blocks??[])as Record<string,unknown>[]).sort((a,b)=>Number(a.position)-Number(b.position)).map(mapBlock)}))}));return{id:String(row.id),title:String(row.title),description:String(row.description??''),cover:`linear-gradient(135deg,${String(row.accent_color??'#3AC3A6')},#142d39)`,tag:'33',status:row.status==='published'?'Опубликован':'Черновик',students:0,progress:0,updated:new Date(String(row.updated_at)).toLocaleDateString('ru-RU'),modules}}
async function resolveAudioUrls(){await Promise.all(courses.value.flatMap(course=>course.modules.flatMap(module=>module.lessons.flatMap(lesson=>lesson.blocks.filter(block=>block.audioPath).map(async block=>{try{block.audioUrl=await createLessonAudioUrl(block.audioPath!)}catch{block.audioUrl=''}})))))}
async function hydrate(){if(!isSupabaseConfigured)return;const auth=useAuthStore();loading.value=true;loadError.value='';try{if(!auth.organization)await auth.loadOrganization();if(!auth.organization||!auth.user){courses.value=[];return}const seedKey='english-engine-seeded-v1-'+auth.organization.id;if(localStorage.getItem(seedKey)!=='true'){await seedEnglishEngineCourse(auth.organization.id,auth.user.id);localStorage.setItem(seedKey,'true')}const{data,error}=await requireSupabase().from('courses').select('id,title,description,status,accent_color,updated_at,course_modules(id,title,position,lessons(id,title,duration_minutes,status,position,lesson_blocks(id,block_type,title,public_content,private_content,is_required,position)))').eq('organization_id',auth.organization.id).order('updated_at',{ascending:false});if(error)throw error;courses.value=((data??[])as unknown as Record<string,unknown>[]).map(mapDbCourse);await resolveAudioUrls()}catch(error){loadError.value=error instanceof Error?error.message:'Не удалось загрузить курс'}finally{loading.value=false}}
async function createCourse(title:string,description:string){if(!isSupabaseConfigured){const id=`course-${Date.now()}`;courses.value.unshift({id,title,description,cover:'linear-gradient(135deg,#176452,#3ac3a6)',tag:title.slice(0,2).toUpperCase(),status:'Черновик',students:0,progress:0,updated:'Только что',modules:[]});return id}const auth=useAuthStore();if(!auth.organization||!auth.user)throw new Error('Организация пользователя не найдена');const{data,error}=await requireSupabase().from('courses').insert({organization_id:auth.organization.id,owner_id:auth.user.id,title,description,slug:slugify(title,'course'),language_code:'ru'}).select('id').single();if(error)throw error;await hydrate();return String(data.id)}
async function addModule(courseId:string,title='Новый модуль'){const course=findCourse(courseId);if(!course)return;if(!isSupabaseConfigured){course.modules.push({id:`module-${Date.now()}`,title,open:true,lessons:[]});return}const{error}=await requireSupabase().from('course_modules').insert({course_id:courseId,title,position:course.modules.length});if(error)throw error;await hydrate()}
async function addLesson(courseId:string,moduleId:string,title='Новый урок'){const module=findCourse(courseId)?.modules.find(item=>item.id===moduleId);if(!module)return;if(!isSupabaseConfigured){const id=`lesson-${Date.now()}`;module.lessons.push({id,title,duration:45,status:'Черновик',blocks:[]});return id}const{data,error}=await requireSupabase().from('lessons').insert({course_id:courseId,module_id:moduleId,title,slug:slugify(title,'lesson'),duration_minutes:45,position:module.lessons.length}).select('id').single();if(error)throw error;await hydrate();return String(data.id)}
const defaults:Record<BlockType,[string,string,Partial<LessonBlock>?]>={heading:['Заголовок','Новый раздел'],text:['Текст','Добавьте объяснение и примеры.'],callout:['Важно','Добавьте формулу.'],grammar:['Теория','Подробно объясните правило.'],vocabulary:['Словарь','Добавьте слова и примеры.'],practice:['Практика','Добавьте активное задание.'],audio:['Аудирование','Прослушайте запись.',{transcript:'Add the English transcript here.'}],conversation:['Разговор с носителем','Опишите ситуацию разговора.',{role:'Житель США',starter:'Начните разговор на английском.',sampleAnswer:'Sample answer'}],flashcards:['Карточки','Добавьте карточки.',{cards:[]}],error_correction:['Клиника ошибок','Добавьте типичные ошибки.',{corrections:[]}],translation:['Перевод','Переведите текст.',{sourceText:'Исходный текст',targetText:'Model translation'}],single_choice:['Вопрос','Введите вопрос',{options:['Вариант 1','Вариант 2','Вариант 3','Вариант 4'],correctOption:0,explanation:'Объяснение ответа.'}]}
function publicContent(item:LessonBlock){if(item.type==='single_choice')return{question:item.content,options:item.options?.map((label,index)=>({id:String(index),label}))};if(item.type==='conversation')return{kind:'conversation',content:item.content,role:item.role,prompt:item.prompt,starter:item.starter,sampleAnswer:item.sampleAnswer};if(item.type==='flashcards')return{kind:'flashcards',content:item.content,cards:item.cards};if(item.type==='error_correction')return{kind:'error_correction',content:item.content,items:item.corrections};if(item.type==='translation')return{kind:'translation',content:item.content,sourceText:item.sourceText,questions:item.comprehensionQuestions};return{kind:item.type,content:item.content,audioPath:item.audioPath,audioUrl:item.audioPath?undefined:item.audioUrl,transcript:item.transcript}}
function privateContent(item:LessonBlock){return item.type==='single_choice'?{correctOption:item.correctOption??0,explanation:item.explanation??''}:item.type==='translation'?{targetText:item.targetText}:{} }
async function addBlock(lessonId:string,type:BlockType){const found=findLesson(lessonId);if(!found)return;const[title,content,extra={}]=defaults[type];if(!isSupabaseConfigured){found.lesson.blocks.push(makeBlock(`block-${Date.now()}`,type,title,content,extra));return}const item=makeBlock('',type,title,content,extra);const{error}=await requireSupabase().from('lesson_blocks').insert({course_id:found.course.id,lesson_id:lessonId,block_type:dbType(type),title,public_content:publicContent(item),private_content:privateContent(item),position:found.lesson.blocks.length});if(error)throw error;await hydrate()}
async function saveLesson(lessonId:string){const found=findLesson(lessonId);if(!found||!isSupabaseConfigured)return;const{error}=await requireSupabase().from('lessons').update({title:found.lesson.title,duration_minutes:found.lesson.duration,status:found.lesson.status==='Опубликован'?'published':'draft'}).eq('id',lessonId);if(error)throw error}
async function saveBlock(lessonId:string,blockId:string){if(!isSupabaseConfigured)return;const item=findLesson(lessonId)?.lesson.blocks.find(block=>block.id===blockId);if(!item)return;const{error}=await requireSupabase().from('lesson_blocks').update({title:item.title,public_content:publicContent(item),private_content:privateContent(item),is_required:item.required}).eq('id',blockId);if(error)throw error}
async function uploadAudio(lessonId:string,blockId:string,file:File){const found=findLesson(lessonId),item=found?.lesson.blocks.find(block=>block.id===blockId);if(!found||!item||item.type!=='audio')throw new Error('Выберите аудиоблок');const auth=useAuthStore();const uploaded=await uploadLessonAudio({organizationId:auth.organization?.id??'demo',courseId:found.course.id,lessonId,blockId,file});item.audioPath=uploaded.path;item.audioUrl=uploaded.url;await saveBlock(lessonId,blockId)}
async function removeBlock(lessonId:string,blockId:string){const found=findLesson(lessonId);if(found)found.lesson.blocks=found.lesson.blocks.filter(item=>item.id!==blockId);if(isSupabaseConfigured){const{error}=await requireSupabase().from('lesson_blocks').delete().eq('id',blockId);if(error)throw error}}
async function saveCourse(courseId:string){const course=findCourse(courseId);if(!course||!isSupabaseConfigured)return;const{error}=await requireSupabase().from('courses').update({title:course.title,description:course.description}).eq('id',courseId);if(error)throw error;course.updated='Только что'}
async function deleteCourse(courseId:string){const index=courses.value.findIndex(course=>course.id===courseId);if(index<0)return;if(isSupabaseConfigured){const{error}=await requireSupabase().from('courses').delete().eq('id',courseId);if(error)throw error}courses.value.splice(index,1)}
async function publishCourse(id:string){if(!isSupabaseConfigured){const course=findCourse(id);if(course)course.status='Опубликован';return}const{error}=await requireSupabase().rpc('publish_course',{p_course_id:id,p_changelog:'Published from Course Platform'});if(error)throw error;await hydrate()}
async function persistCourseOrder(courseId:string){const course=findCourse(courseId);if(!course||!isSupabaseConfigured)return;await Promise.all(course.modules.map((module,position)=>requireSupabase().from('course_modules').update({position}).eq('id',module.id)));await Promise.all(course.modules.flatMap(module=>module.lessons.map((lesson,position)=>requireSupabase().from('lessons').update({module_id:module.id,position}).eq('id',lesson.id))))}
async function persistBlockOrder(lessonId:string){const found=findLesson(lessonId);if(!found||!isSupabaseConfigured)return;await Promise.all(found.lesson.blocks.map((item,position)=>requireSupabase().from('lesson_blocks').update({position}).eq('id',item.id)))}
function resetDemo(){if(!isSupabaseConfigured){courses.value=structuredClone(demoCourses);localStorage.removeItem('cursor-courses-v3')}}
return{courses,learners,loading,loadError,totalLessons,findCourse,findLesson,hydrate,createCourse,addModule,addLesson,addBlock,saveLesson,saveBlock,uploadAudio,removeBlock,saveCourse,deleteCourse,publishCourse,persistCourseOrder,persistBlockOrder,resetDemo}})