import{computed,ref,watch}from'vue'
import{defineStore}from'pinia'
import type{BlockType,Course,Learner,LessonBlock}from'@/types/course'
import{isSupabaseConfigured,requireSupabase}from'@/services/supabase'
import{useAuthStore}from'@/stores/auth'
import{slugify}from'@/utils/slugify'
import{buildEnglishB2DemoCourse,seedEnglishB2Course}from'@/services/seed-english-course'
import{createLessonAudioUrl,uploadLessonAudio}from'@/services/lesson-audio.service'

const makeBlock=(id:string,type:BlockType,title:string,content:string,extra:Partial<LessonBlock>={}):LessonBlock=>({id,type,title,content,required:true,...extra})
const demoCourses:Course[]=[buildEnglishB2DemoCourse()]
const demoLearners:Learner[]=[]

export const useCourseStore=defineStore('courses',()=>{
 const saved=localStorage.getItem('cursor-courses-v2')
 const courses=ref<Course[]>(isSupabaseConfigured?[]:(saved?JSON.parse(saved):demoCourses))
 const learners=ref<Learner[]>(isSupabaseConfigured?[]:demoLearners)
 const loading=ref(false);const loadError=ref('')
 if(!isSupabaseConfigured)watch(courses,value=>localStorage.setItem('cursor-courses-v2',JSON.stringify(value)),{deep:true})
 const totalLessons=computed(()=>courses.value.reduce((sum,c)=>sum+c.modules.reduce((s,m)=>s+m.lessons.length,0),0))
 const findCourse=(id:string)=>courses.value.find(course=>course.id===id)
 const findLesson=(id:string)=>{for(const course of courses.value)for(const module of course.modules){const lesson=module.lessons.find(item=>item.id===id);if(lesson)return{course,module,lesson}}}

 function mapDbCourse(row:Record<string,unknown>):Course{
  const modules=((row.course_modules??[])as Record<string,unknown>[]).sort((a,b)=>Number(a.position)-Number(b.position)).map(module=>({id:String(module.id),title:String(module.title),open:true,lessons:((module.lessons??[])as Record<string,unknown>[]).sort((a,b)=>Number(a.position)-Number(b.position)).map(lesson=>({id:String(lesson.id),title:String(lesson.title),duration:Number(lesson.duration_minutes),status:lesson.status==='published'?'Опубликован' as const:'Черновик' as const,blocks:((lesson.lesson_blocks??[])as Record<string,unknown>[]).sort((a,b)=>Number(a.position)-Number(b.position)).map(item=>{const pub=(item.public_content??{})as Record<string,unknown>;const priv=(item.private_content??{})as Record<string,unknown>;return{id:String(item.id),type:item.block_type==='rich_text'?'text':String(item.block_type)as BlockType,title:String(item.title??''),content:String(pub.content??pub.text??pub.question??''),required:Boolean(item.is_required),options:Array.isArray(pub.options)?pub.options.map(option=>typeof option==='string'?option:String((option as Record<string,unknown>).label??'')):undefined,correctOption:typeof priv.correctOption==='number'?priv.correctOption:undefined,explanation:String(priv.explanation??''),audioPath:String(pub.audioPath??''),audioUrl:String(pub.audioUrl??''),transcript:String(pub.transcript??'')}})}))}))
  return{id:String(row.id),title:String(row.title),description:String(row.description??''),cover:`linear-gradient(135deg,${String(row.accent_color??'#8B6CFF')},#34236d)`,tag:String(row.title).slice(0,2).toUpperCase(),status:row.status==='published'?'Опубликован':'Черновик',students:0,progress:0,updated:new Date(String(row.updated_at)).toLocaleDateString('ru-RU'),modules}
 }
 async function resolveAudioUrls(){await Promise.all(courses.value.flatMap(course=>course.modules.flatMap(module=>module.lessons.flatMap(lesson=>lesson.blocks.filter(block=>block.audioPath).map(async block=>{try{block.audioUrl=await createLessonAudioUrl(block.audioPath!)}catch{block.audioUrl=''}})))))}
 async function hydrate(){if(!isSupabaseConfigured)return;const auth=useAuthStore();loading.value=true;loadError.value='';try{if(!auth.organization)await auth.loadOrganization();if(!auth.organization||!auth.user){courses.value=[];return}await seedEnglishB2Course(auth.organization.id,auth.user.id);const{data,error}=await requireSupabase().from('courses').select('id,title,description,status,accent_color,updated_at,course_modules(id,title,position,lessons(id,title,duration_minutes,status,position,lesson_blocks(id,block_type,title,public_content,private_content,is_required,position)))').eq('organization_id',auth.organization.id).order('updated_at',{ascending:false});if(error)throw error;courses.value=((data??[])as unknown as Record<string,unknown>[]).map(mapDbCourse);await resolveAudioUrls();const{data:enrollments,error:ee}=await requireSupabase().from('course_enrollments').select('id,status,progress_percent,learners(id,display_name,email),courses(title)');if(!ee)learners.value=((enrollments??[])as unknown as Record<string,unknown>[]).map(row=>{const learner=row.learners as Record<string,unknown>;const course=row.courses as Record<string,unknown>;return{id:String(learner.id),name:String(learner.display_name??learner.email??'Ученик'),email:String(learner.email??''),course:String(course.title??''),progress:Number(row.progress_percent),status:row.status==='completed'?'Завершил':'Активен'}})}catch(error){loadError.value=error instanceof Error?error.message:'Не удалось загрузить данные'}finally{loading.value=false}}

 async function createCourse(title:string,description:string){if(!isSupabaseConfigured){const id=`course-${Date.now()}`;courses.value.unshift({id,title,description,cover:'linear-gradient(135deg,#553bb0,#8b6cff)',tag:title.slice(0,2).toUpperCase(),status:'Черновик',students:0,progress:0,updated:'Только что',modules:[]});return id}const auth=useAuthStore();if(!auth.organization||!auth.user)throw new Error('Организация пользователя не найдена');const{data,error}=await requireSupabase().from('courses').insert({organization_id:auth.organization.id,owner_id:auth.user.id,title,description,slug:slugify(title,'course'),language_code:'ru'}).select('id').single();if(error)throw error;await hydrate();return String(data.id)}
 async function addModule(courseId:string,title='Новый модуль'){const course=findCourse(courseId);if(!course)return;if(!isSupabaseConfigured){course.modules.push({id:`module-${Date.now()}`,title,open:true,lessons:[]});return}const{error}=await requireSupabase().from('course_modules').insert({course_id:courseId,title,position:course.modules.length});if(error)throw error;await hydrate()}
 async function addLesson(courseId:string,moduleId:string,title='Новый урок'){const module=findCourse(courseId)?.modules.find(item=>item.id===moduleId);if(!module)return;if(!isSupabaseConfigured){const id=`lesson-${Date.now()}`;module.lessons.push({id,title,duration:45,status:'Черновик',blocks:[]});return id}const{data,error}=await requireSupabase().from('lessons').insert({course_id:courseId,module_id:moduleId,title,slug:slugify(title,'lesson'),duration_minutes:45,position:module.lessons.length}).select('id').single();if(error)throw error;await hydrate();return String(data.id)}
 async function addBlock(lessonId:string,type:BlockType){const found=findLesson(lessonId);if(!found)return;const defaults:Record<BlockType,[string,string]>={heading:['Заголовок','Новый раздел'],text:['Текст','Добавьте объяснение и примеры.'],callout:['Важно','Добавьте формулу или важное замечание.'],grammar:['Теория грамматики','Опишите правило, структуру и случаи употребления.'],vocabulary:['Словарь','Добавьте слова, перевод и примеры употребления.'],audio:['Аудирование','Прослушайте запись и выполните задания.'],single_choice:['Вопрос 1 из 4','Введите вопрос']};const[title,content]=defaults[type];const extra:Partial<LessonBlock>=type==='single_choice'?{options:['Вариант 1','Вариант 2','Вариант 3','Вариант 4'],correctOption:0,explanation:'Объясните правильный ответ.'}:type==='audio'?{transcript:'Add the English transcript here.'}:{};if(!isSupabaseConfigured){found.lesson.blocks.push(makeBlock(`block-${Date.now()}`,type,title,content,extra));return}const publicContent=type==='single_choice'?{question:content,options:extra.options!.map((label,index)=>({id:String(index),label}))}:{content,transcript:extra.transcript};const privateContent=type==='single_choice'?{correctOption:0,explanation:extra.explanation}:{};const{error}=await requireSupabase().from('lesson_blocks').insert({course_id:found.course.id,lesson_id:lessonId,block_type:type==='text'?'rich_text':type,title,public_content:publicContent,private_content:privateContent,position:found.lesson.blocks.length});if(error)throw error;await hydrate()}
 async function saveLesson(lessonId:string){const found=findLesson(lessonId);if(!found||!isSupabaseConfigured)return;const{error}=await requireSupabase().from('lessons').update({title:found.lesson.title,duration_minutes:found.lesson.duration,status:found.lesson.status==='Опубликован'?'published':'draft'}).eq('id',lessonId);if(error)throw error}
 async function saveBlock(lessonId:string,blockId:string){if(!isSupabaseConfigured)return;const item=findLesson(lessonId)?.lesson.blocks.find(block=>block.id===blockId);if(!item)return;const publicContent=item.type==='single_choice'?{question:item.content,options:item.options?.map((label,index)=>({id:String(index),label}))}:{content:item.content,audioPath:item.audioPath,audioUrl:item.audioPath?undefined:item.audioUrl,transcript:item.transcript};const privateContent=item.type==='single_choice'?{correctOption:item.correctOption??0,explanation:item.explanation??''}:{};const{error}=await requireSupabase().from('lesson_blocks').update({title:item.title,public_content:publicContent,private_content:privateContent,is_required:item.required}).eq('id',blockId);if(error)throw error}
 async function uploadAudio(lessonId:string,blockId:string,file:File){const found=findLesson(lessonId);const item=found?.lesson.blocks.find(block=>block.id===blockId);if(!found||!item||item.type!=='audio')throw new Error('Выберите аудиоблок');const auth=useAuthStore();const uploaded=await uploadLessonAudio({organizationId:auth.organization?.id??'demo',courseId:found.course.id,lessonId,blockId,file});item.audioPath=uploaded.path;item.audioUrl=uploaded.url;await saveBlock(lessonId,blockId)}
 async function removeBlock(lessonId:string,blockId:string){const found=findLesson(lessonId);if(found)found.lesson.blocks=found.lesson.blocks.filter(item=>item.id!==blockId);if(isSupabaseConfigured){const{error}=await requireSupabase().from('lesson_blocks').delete().eq('id',blockId);if(error)throw error}}
 async function saveCourse(courseId:string){const course=findCourse(courseId);if(!course||!isSupabaseConfigured)return;const{error}=await requireSupabase().from('courses').update({title:course.title,description:course.description}).eq('id',courseId);if(error)throw error;course.updated='Только что'}
 async function publishCourse(id:string){if(!isSupabaseConfigured){const course=findCourse(id);if(course)course.status='Опубликован';return}const{error}=await requireSupabase().rpc('publish_course',{p_course_id:id,p_changelog:'Published from Course Platform'});if(error)throw error;await hydrate()}
 async function persistCourseOrder(courseId:string){const course=findCourse(courseId);if(!course||!isSupabaseConfigured)return;try{await Promise.all(course.modules.map((module,position)=>requireSupabase().from('course_modules').update({position}).eq('id',module.id).then(({error})=>{if(error)throw error})));await Promise.all(course.modules.flatMap(module=>module.lessons.map((lesson,position)=>requireSupabase().from('lessons').update({module_id:module.id,position}).eq('id',lesson.id).then(({error})=>{if(error)throw error}))))}catch(error){await hydrate();throw error}}
 async function persistBlockOrder(lessonId:string){const found=findLesson(lessonId);if(!found||!isSupabaseConfigured)return;try{await Promise.all(found.lesson.blocks.map((item,position)=>requireSupabase().from('lesson_blocks').update({position}).eq('id',item.id).then(({error})=>{if(error)throw error})))}catch(error){await hydrate();throw error}}
 function resetDemo(){if(!isSupabaseConfigured){courses.value=structuredClone(demoCourses);localStorage.removeItem('cursor-courses-v2')}}
 return{courses,learners,loading,loadError,totalLessons,findCourse,findLesson,hydrate,createCourse,addModule,addLesson,addBlock,saveLesson,saveBlock,uploadAudio,removeBlock,saveCourse,publishCourse,persistCourseOrder,persistBlockOrder,resetDemo}
})